server:
  port: 8085

spring:
  application:
    name: customer
  datasource:
    username: 'maltrkawi'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true